CREATE TABLE IF NOT EXISTS MediaSyncs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    chatId INTEGER NOT NULL,
    messageId INTEGER NOT NULL,
    hash TEXT NOT NULL,
    backupType TEXT NOT NULL DEFAULT 'Immich',
    mediaId TEXT,
    existed BOOLEAN NOT NULL DEFAULT 0,
    updated BOOLEAN NOT NULL DEFAULT 0,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(chatId, messageId)
    UNIQUE(chatId, hash)
)